# Generated by Django 5.0.3 on 2024-03-29 05:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('incident', '0002_rename_task_ticket_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='ticket',
            old_name='complete',
            new_name='solved',
        ),
    ]
