# Generated by Django 5.0.3 on 2024-04-03 07:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('incident', '0003_rename_complete_ticket_solved'),
    ]

    operations = [
        migrations.AddField(
            model_name='ticket',
            name='atm_id',
            field=models.CharField(default=0, max_length=20),
        ),
        migrations.AddField(
            model_name='ticket',
            name='city',
            field=models.CharField(default='', max_length=30),
        ),
        migrations.AddField(
            model_name='ticket',
            name='updated',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='ticket',
            name='ticket_details',
            field=models.CharField(default='', max_length=200),
        ),
    ]
