# Generated by Django 5.0.3 on 2024-04-22 09:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('incident', '0004_ticket_atm_id_ticket_city_ticket_updated_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='ticket',
            name='updated_by',
            field=models.CharField(default='EPS User', max_length=20),
        ),
        migrations.AlterField(
            model_name='ticket',
            name='atm_id',
            field=models.CharField(default='', max_length=20),
        ),
    ]
