# Generated by Django 5.0.3 on 2024-04-22 12:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('incident', '0005_ticket_updated_by_alter_ticket_atm_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ticket',
            name='atm_id',
            field=models.CharField(default='BLANK', max_length=20),
        ),
        migrations.AlterField(
            model_name='ticket',
            name='city',
            field=models.CharField(default='BLANK', max_length=30),
        ),
        migrations.AlterField(
            model_name='ticket',
            name='ticket_details',
            field=models.CharField(default='BLANK', max_length=200),
        ),
    ]
